project:
  type: website
  output-dir: _site
  resources: 
    - posts/
    - "*.qmd"
    - "*.png"

website:
  title: "Maple60â€™s website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
  draft-mode: gone # https://quarto.org/docs/websites/website-drafts.html

format:
  html:
    theme:
      - default
      - custom.scss
    toc: true
    code-link: true
    code-line-numbers: false 
    code-annotations: false
    code-copy: true

execute:
  freeze: auto # re-render only when source changes
